import { stripIndent } from "common-tags";

export const BLANK_LINE_IDENTIFIER = "// ___BLANK_LINE_TO_BE_REPLACED___";

export const NON_EDITABLE_FILE_HEADER = stripIndent`
	// Code generated by prismic-typescript-generator. DO NOT EDIT.
	${BLANK_LINE_IDENTIFIER}
`;
